# Generated by Django 5.0.6 on 2024-06-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0002_alter_breed_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
