# Generated by Django 5.0.6 on 2024-06-09 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petcare',
            options={'ordering': ['title']},
        ),
    ]
